Repository sparcs-kaist/otlplus-server, pull requests merged in 2024-03, with the labels that each got.

#62 Issue/55/planner
  src/app.module.ts
  src/common/interfaces/constants/additional.track.response.dto.ts
  src/common/interfaces/dto/planner/planner.request.dto.ts
  src/common/interfaces/dto/planner/planner.response.dto.ts
  src/common/interfaces/dto/planner_item/arbitrary.response.dto.ts
  src/common/interfaces/dto/planner_item/future.reponse.dto.ts
  src/common/interfaces/dto/planner_item/taken.response.dto.ts
  src/common/interfaces/dto/track/additional.response.dto.ts
  src/common/interfaces/dto/track/general.response.dto.ts
  src/common/interfaces/dto/track/major.response.dto.ts
  src/common/interfaces/serializer/planner.item.serializer.ts
  src/common/interfaces/serializer/planner.serializer.ts
  src/common/interfaces/serializer/track.serializer.ts
  src/common/schemaTypes/types.ts
  src/common/utils/method.utils.ts
  src/modules/planners/planners.controller.ts
  src/modules/planners/planners.module.ts
  src/modules/planners/planners.service.ts
  src/modules/tracks/tracks.controller.ts
  src/modules/tracks/tracks.module.ts
  src/modules/tracks/tracks.service.ts
  src/prisma/prisma.module.ts
  src/prisma/repositories/planner.repository.ts
  src/prisma/repositories/track.repository.ts
Labels: feat

#81 refactor: repository dependency injection
  src/modules/feeds/feeds.service.ts
  src/prisma/repositories/feeds.repository.ts
  src/prisma/repositories/review.repository.ts
  src/prisma/repositories/user.repository.ts
Labels: refactor

#51 feat: add rates API
  package-lock.json
  package.json
  src/app.module.ts
  src/common/interfaces/IRate.ts
  src/common/interfaces/serializer/rate.serializer.ts
  src/modules/rates/rates.controller.ts
  src/modules/rates/rates.module.ts
  src/modules/rates/rates.service.ts
  src/prisma/migrations/20240306130709_add_default_date_for_rate/migration.sql
  src/prisma/repositories/rates.repository.ts
  src/prisma/schema.prisma
  src/settings.ts
Labels: feat

#78 refactor: get courseuser
  src/common/schemaTypes/types.ts
  src/modules/courses/courses.controller.ts
  src/modules/courses/courses.service.ts
  src/modules/user/user.service.ts
  src/prisma/repositories/course.repository.ts
Labels: refactor

#90 fix: taken lecture does not exist
  src/modules/feeds/feeds.service.ts
Labels: bug

#96 feat:add future item
  src/common/interfaces/IPlanner.ts
  src/modules/planners/planners.controller.ts
  src/modules/planners/planners.service.ts
  src/prisma/repositories/planner.repository.ts
Labels: feat
